-- Additional communities to expand to 60+ total
-- Adding communities that aren't in the current 24

-- Learning & Self-Improvement (Category 5) - Add more
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(5, 'Online Course & MOOC Communities', 'Learners around specific educational platforms and subjects', '["Coursera study groups", "edX communities", "MasterClass enthusiasts", "Khan Academy"]', 2900000, 'medium', 'stable', '["Facebook", "Reddit", "Discord", "YouTube"]'),
(5, 'Self-Help & Personal Development', 'Communities focused on personal growth methodologies', '["productivity systems", "habit tracking", "specific self-help book clubs", "life coaching"]', 3200000, 'high', 'growing', '["Instagram", "TikTok", "YouTube", "Pinterest"]'),
(5, 'Academic & Research Communities', 'Higher education and research-focused groups', '["PhD students", "specific academic disciplines", "research methodology", "academic writing"]', 1800000, 'medium', 'stable', '["Reddit", "Twitter/X", "LinkedIn", "YouTube"]'),
(5, 'Skill-Specific Learning', 'Communities around particular skill development', '["public speaking", "negotiation skills", "speed reading", "memory techniques", "critical thinking"]', 2400000, 'high', 'growing', '["YouTube", "Reddit", "LinkedIn", "Instagram"]'),
(5, 'Philosophy & Critical Thinking', 'Intellectual discussion and philosophical exploration communities', '["stoicism", "existentialism", "debate communities", "ethics discussions", "logic puzzles"]', 1600000, 'medium', 'stable', '["Reddit", "YouTube", "Twitter/X", "Discord"]'),
(5, 'Entrepreneurship & Startup Culture', 'Business building and startup communities', '["indie hackers", "specific startup accelerators", "solopreneur communities", "business model innovation"]', 2100000, 'high', 'growing', '["Twitter/X", "LinkedIn", "YouTube", "Reddit"]');

-- Hobbies & Specialized Interests (Category 6) - Add more
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(6, 'Collecting Communities', 'Enthusiasts who collect specific items or categories', '["vintage electronics", "rare books", "coin collecting", "stamp collecting", "antique furniture", "vinyl records"]', 3400000, 'high', 'stable', '["Instagram", "Facebook", "Reddit", "YouTube"]'),
(6, 'Model Building & Scale Models', 'Communities focused on building detailed scale models', '["model trains", "airplane models", "car models", "architectural models", "dioramas"]', 1900000, 'high', 'stable', '["YouTube", "Facebook", "Instagram", "Reddit"]'),
(6, 'Automotive Enthusiasts', 'Car culture and automotive hobby communities', '["specific car brands", "classic cars", "modification communities", "racing enthusiasts", "motorcycle groups"]', 4200000, 'very_high', 'growing', '["Instagram", "YouTube", "Facebook", "Reddit"]'),
(6, 'Aviation & Space Enthusiasts', 'Communities interested in flight and space exploration', '["pilot communities", "aircraft spotting", "space exploration", "drone flying", "amateur rocketry"]', 2300000, 'high', 'growing', '["YouTube", "Reddit", "Instagram", "Facebook"]'),
(6, 'Amateur Radio & Electronics', 'Radio communication and electronics hobbyists', '["ham radio operators", "electronics repair", "circuit building", "radio experimentation"]', 1200000, 'medium', 'stable', '["YouTube", "Reddit", "Facebook", "Discord"]'),
(6, 'Genealogy & Family History', 'Communities researching family history and ancestry', '["DNA testing", "historical research", "family tree building", "heritage preservation"]', 2800000, 'medium', 'stable', '["Facebook", "YouTube", "Reddit", "Pinterest"]'),
(6, 'Puzzle & Brain Game Communities', 'Communities around mental challenges and puzzles', '["crossword enthusiasts", "sudoku", "escape room design", "logic puzzles", "chess communities"]', 2100000, 'medium', 'stable', '["Reddit", "YouTube", "Facebook", "Discord"]'),
(6, 'Woodworking & Craftsmanship', 'Traditional craft and woodworking communities', '["furniture making", "carving", "restoration", "traditional techniques", "tool collecting"]', 2600000, 'high', 'growing', '["YouTube", "Instagram", "Pinterest", "Facebook"]'),
(6, 'Astronomy & Stargazing', 'Amateur astronomy and space observation communities', '["telescope users", "astrophotography", "celestial events", "planetarium enthusiasts"]', 1700000, 'high', 'growing', '["Reddit", "Instagram", "YouTube", "Facebook"]'),
(6, 'Music Production & Audio', 'Communities focused on music creation and audio engineering', '["home recording", "beat making", "podcast production", "sound design", "vinyl collecting"]', 2900000, 'very_high', 'growing', '["YouTube", "Reddit", "Instagram", "TikTok"]');

-- Lifestyle & Values-Driven (Category 7) - Add more
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(7, 'Minimalism & Intentional Living', 'Communities focused on simplified, purposeful living', '["minimalist lifestyle", "decluttering", "intentional consumption", "simple living", "digital minimalism"]', 3800000, 'high', 'growing', '["Instagram", "YouTube", "TikTok", "Pinterest"]'),
(7, 'Spiritual & New Age Communities', 'Alternative spirituality and wellness practices', '["crystal healing", "astrology", "meditation practices", "energy healing", "tarot communities"]', 3600000, 'very_high', 'growing', '["TikTok", "Instagram", "YouTube", "Pinterest"]'),
(7, 'Alternative Lifestyle Choices', 'Non-conventional living arrangements and lifestyles', '["van life", "tiny house living", "off-grid living", "nomadic communities", "co-housing"]', 2400000, 'high', 'exploding', '["Instagram", "YouTube", "TikTok", "Facebook"]'),
(7, 'Ethical Consumption & Fair Trade', 'Conscious consumer communities focused on ethical purchasing', '["fair trade products", "ethical fashion", "cruelty-free beauty", "local sourcing", "B-corp support"]', 2900000, 'high', 'growing', '["Instagram", "Pinterest", "YouTube", "TikTok"]'),
(7, 'Digital Privacy & Rights', 'Communities advocating for digital rights and privacy', '["data privacy", "open source software", "digital rights activism", "surveillance resistance"]', 1600000, 'high', 'growing', '["Reddit", "Twitter/X", "YouTube", "Discord"]'),
(7, 'Slow Living & Mindful Consumption', 'Communities embracing slower-paced, mindful lifestyles', '["slow fashion", "mindful eating", "seasonal living", "analog hobbies", "digital detox"]', 3100000, 'high', 'growing', '["Instagram", "Pinterest", "YouTube", "TikTok"]'),
(7, 'Community Building & Mutual Aid', 'Groups focused on building stronger local communities', '["neighborhood organizing", "mutual aid networks", "community gardens", "local business support"]', 2200000, 'medium', 'growing', '["Facebook", "Instagram", "Twitter/X", "YouTube"]'),
(7, 'Frugal Living & Financial Independence', 'Communities focused on financial freedom through intentional spending', '["FIRE movement", "frugal living", "budget optimization", "debt-free living", "early retirement"]', 2700000, 'high', 'exploding', '["Reddit", "YouTube", "TikTok", "Instagram"]'),
(7, 'Prepping & Self-Sufficiency', 'Communities focused on emergency preparedness and self-reliance', '["emergency preparedness", "homesteading", "survivalism", "self-sufficiency", "disaster planning"]', 1800000, 'high', 'growing', '["YouTube", "Reddit", "Facebook", "Instagram"]');

-- Niche Social & Identity Groups (Category 8) - Add more
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(8, 'LGBTQ+ Subcultures & Identity', 'Diverse LGBTQ+ community groups and identity-based spaces', '["specific identity groups", "pride communities", "queer art", "LGBTQ+ professionals", "chosen family networks"]', 4800000, 'very_high', 'growing', '["TikTok", "Instagram", "Twitter/X", "Discord"]'),
(8, 'Neurodivergent Communities', 'Support and advocacy groups for neurodivergent individuals', '["autism communities", "ADHD support", "dyslexia advocacy", "sensory processing", "neurodiversity celebration"]', 3200000, 'very_high', 'exploding', '["TikTok", "Reddit", "Instagram", "YouTube"]'),
(8, 'Cultural Heritage & Diaspora', 'Communities preserving and celebrating cultural identity', '["specific ethnic communities", "heritage language preservation", "cultural traditions", "diaspora connections"]', 5400000, 'high', 'stable', '["Facebook", "Instagram", "YouTube", "TikTok"]'),
(8, 'Chronic Illness & Disability Support', 'Support communities for specific health conditions and disabilities', '["invisible illness advocacy", "specific condition support", "accessibility activism", "adaptive living"]', 2800000, 'very_high', 'growing', '["Instagram", "TikTok", "Facebook", "YouTube"]'),
(8, 'Age-Specific Communities', 'Communities organized around specific life stages or generations', '["Gen Z culture", "millennial nostalgia", "active seniors", "empty nesters", "young professionals"]', 6200000, 'high', 'stable', '["TikTok", "Instagram", "Facebook", "YouTube"]'),
(8, 'Professional Identity Groups', 'Career and profession-based identity communities', '["women in tech", "minority professionals", "industry-specific groups", "professional mothers", "career changers"]', 3600000, 'high', 'growing', '["LinkedIn", "Instagram", "Twitter/X", "YouTube"]'),
(8, 'Geographic & Regional Identity', 'Location-based identity and community groups', '["specific city cultures", "regional pride", "expat communities", "rural communities", "small town life"]', 4900000, 'medium', 'stable', '["Facebook", "Instagram", "TikTok", "Reddit"]'),
(8, 'Alternative Family Structures', 'Communities around non-traditional family arrangements', '["single parents", "childfree communities", "blended families", "adoption communities", "fertility journey support"]', 2400000, 'high', 'growing', '["Facebook", "Instagram", "Reddit", "YouTube"]'),
(8, 'Hobby-Based Social Groups', 'Social communities that form around shared recreational activities', '["book clubs", "hiking groups", "cooking communities", "pet owner groups", "travel buddy networks"]', 7800000, 'very_high', 'growing', '["Facebook", "Instagram", "Reddit", "TikTok"]'),
(8, 'Religious & Faith Communities', 'Modern faith-based communities and spiritual practices', '["progressive Christianity", "modern paganism", "Buddhist meditation", "interfaith dialogue", "spiritual exploration"]', 3400000, 'high', 'stable', '["Facebook", "YouTube", "Instagram", "Reddit"]');

-- Arts & Creative Expression (Category 1) - Add more
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(1, 'Digital Content Creation', 'Communities focused on video and social media content creation', '["YouTube creators", "TikTok creators", "Instagram content", "podcast production", "live streaming"]', 4200000, 'very_high', 'exploding', '["TikTok", "YouTube", "Instagram", "Discord"]'),
(1, 'Independent Publishing', 'Writers and publishers creating outside traditional publishing', '["self-publishing", "indie authors", "poetry communities", "newsletter writers", "blog creators"]', 2800000, 'high', 'growing', '["Twitter/X", "Instagram", "Medium", "Substack"]'),
(1, 'Street Art & Urban Culture', 'Communities around street art, graffiti, and urban creative expression', '["graffiti artists", "mural painters", "street photography", "urban exploration", "hip-hop culture"]', 3100000, 'very_high', 'growing', '["Instagram", "TikTok", "YouTube", "Reddit"]'),
(1, 'Experimental Arts', 'Communities exploring avant-garde and experimental creative practices', '["performance art", "digital installations", "mixed media", "conceptual art", "art technology"]', 1400000, 'medium', 'growing', '["Instagram", "YouTube", "Twitter/X", "Reddit"]');

-- Gaming & Entertainment (Category 2) - Add more  
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(2, 'Retro Gaming Culture', 'Communities celebrating classic and vintage gaming', '["retro console collecting", "arcade culture", "speed running classic games", "rom hacking", "gaming history"]', 2700000, 'high', 'stable', '["YouTube", "Reddit", "Twitch", "Discord"]'),
(2, 'Mobile Gaming Communities', 'Communities around smartphone and tablet gaming', '["gacha game communities", "puzzle game enthusiasts", "mobile esports", "idle game players"]', 5800000, 'very_high', 'exploding', '["Discord", "Reddit", "YouTube", "TikTok"]'),
(2, 'Game Development & Modding', 'Communities creating and modifying games', '["indie game developers", "game modding", "level design", "game art", "programming communities"]', 2100000, 'high', 'growing', '["Discord", "Reddit", "YouTube", "GitHub"]'),
(2, 'Entertainment Analysis', 'Communities focused on analyzing and discussing entertainment', '["film theory", "TV show analysis", "gaming journalism", "pop culture critique", "media literacy"]', 3400000, 'high', 'growing', '["YouTube", "Reddit", "Twitter/X", "Medium"]');

-- Health, Wellness & Fitness (Category 3) - Add more
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(3, 'Alternative Health Practices', 'Communities exploring non-traditional health and healing methods', '["herbal medicine", "acupuncture", "energy healing", "traditional medicine", "holistic wellness"]', 2900000, 'high', 'growing', '["Instagram", "YouTube", "TikTok", "Facebook"]'),
(3, 'Chronic Condition Support', 'Communities for people managing long-term health conditions', '["diabetes management", "autoimmune support", "pain management", "mental health advocacy"]', 3600000, 'very_high', 'growing', '["Facebook", "Instagram", "Reddit", "YouTube"]'),
(3, 'Fitness Subcultures', 'Specialized fitness communities with distinct cultures', '["powerlifting", "rock climbing", "martial arts", "dance communities", "yoga traditions"]', 4100000, 'very_high', 'growing', '["Instagram", "YouTube", "TikTok", "Reddit"]'),
(3, 'Longevity & Biohacking', 'Communities focused on optimizing health and extending lifespan', '["intermittent fasting", "cold therapy", "nootropics", "sleep optimization", "genetic testing"]', 1800000, 'high', 'exploding', '["YouTube", "Reddit", "Instagram", "Twitter/X"]');

-- Technology & Innovation (Category 4) - Add more
INSERT OR IGNORE INTO communities (category_id, name, description, examples, size_estimate, engagement_level, growth_trend, platform_presence) VALUES
(4, 'Open Source Communities', 'Communities building and maintaining open source software', '["Linux users", "open source developers", "free software advocates", "collaborative coding"]', 2400000, 'high', 'stable', '["GitHub", "Reddit", "Discord", "Twitter/X"]'),
(4, 'Hardware Hacking', 'Communities focused on modifying and creating hardware', '["raspberry pi projects", "arduino communities", "hardware modding", "electronics repair"]', 1900000, 'high', 'growing', '["YouTube", "Reddit", "Discord", "GitHub"]'),
(4, 'Future Tech Enthusiasts', 'Communities excited about emerging technologies', '["quantum computing", "space technology", "biotechnology", "nanotechnology", "fusion energy"]', 2200000, 'medium', 'growing', '["Reddit", "YouTube", "Twitter/X", "LinkedIn"]'),
(4, 'Tech Ethics & Society', 'Communities discussing technology\'s impact on society', '["AI ethics", "data privacy", "tech regulation", "digital rights", "platform governance"]', 1600000, 'high', 'growing', '["Twitter/X", "Reddit", "Medium", "LinkedIn"]');